### ISSUE TITLE
Pey without dagesh (פ / U+05E4) not handled properly

### ISSUE THREAD

**Issue by j0ma** [ibleaman/yiddish-text-tools#1]
Hi and thanks for an awesome library! I was working on [something similar](https://aclanthology.org/2020.lrec-1.119/) a few years ago but never got it worked into a full Python library.

While doing some testing, I noticed that the Unicode character `פ` isn't getting handled properly. Here's an example sentence from the Yiddish portion of the WikiAnn dataset, and what I get after applying `yiddish.transliterate(losh_koydesh=True)` to it:

```python
In [27]: ex_sent
Out[27]: 'ווייטערפירן יידישער טעאלאגישער סעמינאר'

In [28]: rom_ex_sent
Out[28]: 'veyterפirn eydisher telgisher seminr'
```
As we can see the transliteration is not perfect, and the `פ` character ([U+05E4](https://www.compart.com/en/unicode/U+05E4)) is left unchanged in the transliterated text. I realize that there is [some variation among speakers](https://en.wikipedia.org/wiki/Yiddish_orthography#Common_variation) in how פ vs פּ are used but intuitively it seems plausible that the library should be able to handle both. 

Is this the case or is what I'm seeing here somehow a feature, not a bug? Happy to contribute a fix if it's unintentional.

**Comment by ibleaman** [comment]
Thanks for raising the issue! Sorry that I'm just seeing this now.

By "the transliteration is not perfect," do you mean that you were expecting to see `'vayterfirn yidisher teologisher seminar'`? The `transliterate()` function is quite simple in that it just maps Yiddish character sequences onto Latin ones according to the norms of YIVO transliteration, irrespective of word context. The function assumes an input text that follows YIVO's recommended orthography. It does not resolve the ambiguities that arise in variant Yiddish orthographies, even if it is clear to a human reader when `פאר` should be transliterated `'far'` vs. `'por'`. That would require a more advanced approach. Maybe you can contribute something in the future?

The grapheme `פ` doesn't exist without diacritics in the YIVO-recommended orthography (only `פּ` and `פֿ`), but you're right that it shouldn't be left as is in the transliterated string. It'll map onto `f` going forward.
